services:
  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 9000:80

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
  
  