services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-docker
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www/html
      - ./apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mysql
    working_dir: /var/www/html
    networks:
      - laravel_network

  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    networks:
      - laravel_network
      
  npm:
    image: node:22-alpine
    container_name: npm_runner
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
    command: ["tail", "-f", "/dev/null"]  # Keep the container running
    networks:
      - laravel_network

volumes:
  mysql_data:

networks:
  laravel_network:
    driver: bridge
